export const FilterActionType = {
  PRICE_SORT: "PRICE_SORT",
  CATEGORY_SHOT: "CATEGORY_SORT",
  RATING_SORT: "RATING_SORT",
};

export const WishlistActionType = {
  GET_DATA: "GET_DATA",
  ADD_DATA: "ADD_DATA",
  REMOVE_DATA: "REMOVE_DATA",
  CLEAR_DATA: "CLEAR_DATA",
};

export const CartActionType = {
  GET_DATA: "GET_DATA",
  ADD_DATA: "ADD_DATA",
  REMOVE_DATA: "REMOVE_DATA",
  INCREMENT_QUANTITY: "INCREMENT_QUANTITY",
  DECREMENT_QUANTITY: "DECREMENT_QUANTITY",
  CLEAR_DATA: "CLEAR_DATA",
};
